### PR TITLE
fr-FR: 🇫🇷 Adorable French Translation Contribution 🌟

### PR DESCRIPTION
**Pull request by corentios**
Hello!

I'm thrilled to submit my contribution to translate the entire app into French. 🇫🇷 
This involved pushing two files with meticulous attention to detail. ✨

I've made sure that the raw files maintain a spiffy formatting.

## ⚠️ **Note: Potential Wording Mismatch**

As observed in the translation files:

```plaintext
IDS_EXP_CTRLINTF_0_W11      "Windows 11 Command Bar (default)"
IDS_EXP_CTRLINTF_0_W10      "Windows 10 Ribbon (default)"
IDS_EXP_CTRLINTF_1_W11      "Windows 10 Ribbon"
```
It appears that the last key is named W11, but the corresponding wording is "Windows 10 Ribbon." 🤔 Please verify if this is intentional or if there might be a typo. Feel free to adjust accordingly.

Would love your feedback if you want to modify something ! 😊

Cheers,
\- corentios 🌈💻

### CODE REVIEW

**Comment by Amrsatrio** [comment]
image
Unfortunately, there are some strings that are just too long. Due to technical reasons, they have to be short, like the English ones. Is it possible for them to be shortened?

**Comment by corentios** [comment]
@Amrsatrio you can't increase the side bar size ?

If not i can try to find alternative, but it's complicated to be clear

**Comment by Amrsatrio** [comment]
I can, don't worry.

**Comment by Amrsatrio** [comment]
Still need to shorten some strings in the Advanced section. But anyways thank you very much!

**Pull request merged**
