### PR TITLE
Upload zh_Hans translation

### PR DESCRIPTION
**Pull request by FrzMtrsprt**
I have tried compiling ExplorerPatcher with the added translations, and it all seem to work fine. Is there anything I need to add elsewhere?

### CODE REVIEW

**Comment by Amrsatrio** [comment]
Hi! Thanks for the translations! Just confirming, since we use normal ASCII : ( ) ? symbols in Japanese, are full width versions of those symbols ：（）？used in Chinese?

Also, for Simplified Chinese, I'd suggest renaming the file to zh-CN. And it will be zh-TW for Traditional Chinese.

**Comment by zetaloop** [comment]
> Hi! Thanks for the translations! Just confirming, since we use normal ASCII : ( ) ? symbols in Japanese, are full width versions of those symbols ：（）？used in Chinese?
> 
> Also, for Simplified Chinese, I'd suggest renaming the file to zh-CN. And it will be zh-TW for Traditional Chinese.

Yes we usually use the full width `：（）？` in Chinese.
By the way am I a bit late for this place? ;)
#2

**Comment by Amrsatrio** [comment]
Yeah, looks like 😂. I'll merge yours @zetaloop since I prioritize those who have maintained forks for a long time, even better if they have accumulated a lot of stars. Sorry @FrzMtrsprt but you can check the translations from his fork and make another PR.

**Comment by FrzMtrsprt** [comment]
Alright then.

**Pull request closed without merging**
