### PR TITLE
ep_gui.ro-RO

### PR DESCRIPTION
**Pull request by 21124637**
Coman Dănuț
coman.windows@yahoo.com

### CODE REVIEW

**Comment by Amrsatrio** [comment]
There are some strings that are too long (has ... at the end), is it possible for them to be shortened?

image
image
image
image

**Comment by 21124637** [comment]
Is it okay to place the translation here?I made changes to the translation.
    Pe miercuri, 22 noiembrie 2023 la 19:37:31 EET, Amr Satrio ***@***.***> a scris:  
 
 


There are some strings that are too long (has ... at the end), is it possible for them to be shortened?

**Comment by Amrsatrio** [comment]
Yes, you can.

**Comment by Amrsatrio** [comment]
My close Romanian friend has confirmed that they're good already.

**Comment by 21124637** [comment]
I'm glad, thank you!    Pe joi, 23 noiembrie 2023 la 12:27:51 EET, Amr Satrio ***@***.***> a scris:  
 
 


My close Romanian friend has confirmed that they're good already.

**Comment by 21124637** [comment]
Hi,
Translation into Romanian.
 I made some changes to the translation.Please update the translation.
Expect a reply from you.
 Thank you!


    Pe duminică, 10 decembrie 2023 la 19:38:10 EET, Amr Satrio ***@***.***> a scris:  
 
  


Merged #16 into master.

**Comment by 21124637** [comment]
Hi,
Translation into Romanian.I made some changes to the translation.Please update the translation.Expect a reply from you.Thank you!
    Pe vineri, 12 aprilie 2024 la 14:39:03 EEST, Coman Danut ***@***.***> a scris:  
 
  Hi,
Translation into Romanian.
 I made some changes to the translation.Please update the translation.
Expect a reply from you.
 Thank you!


    Pe duminică, 10 decembrie 2023 la 19:38:10 EET, Amr Satrio ***@***.***> a scris:  
 
  


Merged #16 into master.

**Pull request merged**
