### PR TITLE
Fix zh_CN translation

### PR DESCRIPTION
**Pull request by FrzMtrsprt**
1. Translate two untranslated strings
2. Remove unneeded spaces around full width punctuations
3. Change some `（``）` to `(``)` since most strings use half width brackets
4. Unitfy the translation for specific words like `widget`
5. Remove redundant `次` in `IDS_CRASH_BODY`

### CODE REVIEW

**Comment by zetaloop** [comment]
I believe that spaces should be added next to full width quotation marks for visual clarity. Because Windows typically renders full width quotes with the same width as half width quotes, and adding spaces compensates for the missing visual spacing.

文“属性”文。
文 “属性” 文。
image

**Comment by Amrsatrio** [comment]
Feel free to make PRs to make these consistent, as long as they adhere to Windows' style guide. I'm still giving the prerelease couple more days of testing before they can be promoted into Release, and I am also waiting for French and German to be added.

**Comment by FrzMtrsprt** [comment]
> I believe that spaces should be added next to full width quotation marks for visual clarity. Because Windows typically renders full width quotes with the same width as half width quotes, and adding spaces compensates for the missing visual spacing.

Makes sense, but it will look really weird for those who use fonts that renders full width brackets properly. Maybe we can switch to using half width quotes too?

In my opinion, It would be better if we can unify the use of punctuations, either all punctuations in full width, or all unctuations in half width

**Comment by zetaloop** [comment]
> In my opinion, It would be better if we can unify the use of punctuations, either all punctuations in full width, or all unctuations in half width.
>
> However, if we take Microsoft's Chinese localization style guide into account, we still should use full punctuations everywhere, and remove additional spaces. See [Localization Style Guides](https://learn.microsoft.com/en-us/globalization/reference/microsoft-style-guides)

Agree.

Personally, I tend to value the actual presentation. But as the official version of ExplorerPatcher here, it makes sense to follow certain development specifications.

**Comment by Amrsatrio** [comment]
Here in EP, I strive my best to follow the style and terms of the existing text on Windows so that they're consistent.

**Comment by FrzMtrsprt** [comment]
Alright, I will open another PR to replace all of the punctuations to full widths versions, and rephrase some of the informal texts to comply to the style guide.

**Pull request merged**
