### PR TITLE
Add Hungarian (hu-HU) localisation

### PR DESCRIPTION
**Pull request by RedyAu**
Note: I will not be able to compile and test my contribution.

### CODE REVIEW

**Comment by RedyAu** [comment]
Should I force push everything into a single commit when I'm done, or are multiple commits fine?

**Comment by Amrsatrio** [comment]
It's fine, I will squash them at the end once I have time to work with EP.

**Comment by RedyAu** [comment]
Couple questions:
 - Where does the title for the settings window "Properties" come from? From windows, and thus it follows the system language?
 - I think it's best not to translate Advanced options, unless the docs also get translated. I added a new line explaining this on line 390.
   - Is the newline character usable there?
   - Do you agree with this decision?
 - How gracefully does the program handle too long strings; is the main point of testing to see if everything fits?

**Comment by Amrsatrio** [comment]
1. It comes from a certain system DLL that is loaded in the beginning of ZZGUI in GUI.c. If you have the language pack installed, then it shows in that language.
2. The problem is it is translated already on other existing languages which makes this an inconsistency if you decide not to translate.
   - Newlines do not work, unfortunately. The current GUI code is so stiff therefore it does not work.
   - I can't say exactly but I strive for EP to have consistent and natural translations.
3. It just truncates them, so that's why I urge contributors to be able to test themselves. I'd test them for you if I am on my PC right now but I am not at the moment. If there are some translated strings that are simply too long with no way to shorten, I have a piece of code where it enlarges the window width for the said language.

**Comment by RedyAu** [comment]
Thanks!
2. Alright, I will translate the advanced option, then. After that, this should be ready to merge :) // As windows is using formal language, I will keep the translations so as well.

**Comment by RedyAu** [comment]
I did my best to check "by eye" the length of strings that appear in the main window, it should be fine now.

**Comment by Amrsatrio** [comment]
image
Those two strings are kinda problematic in other languages like Dutch, too. Can you shorten them? If you can't, extend the window width if Hungary is set the same way as I do it for Dutch.

**Comment by RedyAu** [comment]
Thank you for testing it. Should fit now.

**Comment by Amrsatrio** [comment]
image
Much better.

**Comment by RedyAu** [comment]
This should make it clearer and still fit :D

**Comment by Amrsatrio** [comment]
image
Yep.

**Comment by RedyAu** [comment]
Great! Thank you for taking the time to verify everything. This is ready to merge as far as I'm concerned. Will be checking back for new strings to translate in the future ;)

**Comment by Amrsatrio** [comment]
image
Looking good?

**Pull request merged**
